### ISSUE TITLE
Bare repo's zijn matig

### ISSUE THREAD

**Issue by V1RE** [mhogeveen/dotfiles#1]
Heb zelf eerst ook een tijd zo'n bare repo gebruikt, maar ben er niet heel erg fan van, kan stow erg aanraden: https://www.youtube.com/watch?v=90xMTKml9O0

**Comment by mhogeveen** [comment]
Ga sowieso een keer kijken naar een betere manier, want dit werkt echt voor geen meter heb ik gemerkt.
Zal Stow een keer bekijken!
